version: '3.8'

services:
  stt-server:
    # Use the latest image from brett's GitHub Container Registry using Github actions
    # Change to my github (jim0237) if I want to build from my github registry
    #image: ghcr.io/bmv234/stt-api-server:latest 
    # Currently Building locally from your source (GitHub Actions disabled)
    build: .
    container_name: stt-server
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
      - ./uploads:/app/uploads
      - ./voice-notes:/app/vnotes  # Voice notes storage
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "--insecure", "https://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
